# Generated by Django 5.2.7 on 2025-11-30 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmotionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emotion', models.CharField(choices=[('angry', 'Angry'), ('disgust', 'Disgust'), ('fear', 'Fear'), ('happy', 'Happy'), ('sad', 'Sad'), ('surprise', 'Surprise'), ('neutral', 'Neutral')], max_length=20)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session_id', models.CharField(blank=True, max_length=100)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emotion_records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
